[package]
name = "tari_json_rpc_proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_app_grpc = {path="../tari_app_grpc"}

jsonrpc-http-server = "17.1.0"
